export const registerURL = "/api/user/register"
export const verifyURL = "/api/user/verify"
export const loginURL = "/api/user/login"
export const googleURL = "/auth/google"
export const facebookURL = "/auth/facebook"
export const profileURL = "/api/user/profile"
export const updatePhoneURL = "/api/user/profile/updatePhone"
export const postAdURL = "/api/postad"
export const adsURL = "/api/ads"
// get single ad based on id
export const singleAdURL = "/api/ads"
export const userAdsURL = "/api/user/ads"
export const relatedAdsURL = "/api/user/relatedads"